### ISSUE TITLE
Linux Issues (All Pluely Linux Distributions)

### ISSUE THREAD

**Issue by iamsrikanthnani** [iamsrikanthnani/pluely#103]
All Linux-related issues for Pluely — including Ubuntu, Fedora, Arch, and other distributions.

This issue will be used to group, reference, and monitor any bugs or inconsistencies specific to Linux environments.

**Comment by ammargadit-pure** [comment]
release v 0.1.5 and v0.1.6 both are not able to detect system devices
There is even a refresh button in v1.6 but it throws an error of user permission - there is no way to enable the permision, neither there is any popup opening

**Comment by Dafi95** [comment]
Ubuntu 24.04 ; Audio Settings ; Microphone/System Audio - No output devices found.
Pluely 0.1.6

---

Section System Audio Capture
Audio Capture Error 
Invalid sample rate 0. Expected 8000-96000 Hz

**Comment by gbrennon** [comment]
pluely v0.1.6 couldnt find the microphone here too

**Comment by svandragt** [comment]
Same but I know I use pipewire which is not supported according to https://pluely.com/download/linux

**Comment by iamsrikanthnani** [comment]
Update:

I’ll be working to address Linux-related issues as I go. Since many users are on macOS and Windows, I’m prioritizing those platforms first.

That said, I’ll be focusing on fixing key Linux issues like microphone, system audio, and cursor problems as soon as possible.

Because there are so many different Linux distributions, it’s difficult to resolve everything at once. I’ll tackle these issues step by step and roll out improvements gradually.

**Comment by iamsrikanthnani** [comment]
### In the latest release, the microphone, system audio, and cursor issues on Linux have been fixed.

If anyone is interested in helping tackle the remaining Linux-distribution-specific issues, contributions are always welcome. 🙌

**Comment by svandragt** [comment]
Thanks for the effort! Still not seeing audio/microphone devices on the latest build, (pipewire on Ubuntu 22.04 LTS). Let me know what diagnostic info you need and I'm happy to support or create a ticket. I ran it from the terminal but no error messages appear for audio related stuff.

**Comment by spirulin** [comment]
On Ubuntu 24.04.3, Pluely doesn't stay on top, even though it's switched on in the settings. I press on my browser to open a website, and it simply disappears into the background. The same happens with other apps too. It doesn't respect the settings. :)

**Comment by gbrennon** [comment]
any updates?

**Comment by iamsrikanthnani** [comment]
@gbrennon Just released [Pluely v0.1.9](https://pluely.com/downloads), hopefully it fixes some issues… and creates new ones for Linux distributions 🥲😄

Please try the latest version and share any issues you run into!

**Comment by gbrennon** [comment]
@iamsrikanthnani im going to verify it soon!

rn im busy with some tasks but later im going to check it

EDIT:

- does it, now, supports pipewire?

**Comment by gbrennon** [comment]
@iamsrikanthnani UI stil arent rendering correctly. it renders blank.

i have experienced this issue using other XFCE DE and i3wm.

is there a discord server for the community?

**Comment by Vellmor** [comment]
<img width="895" height="113" alt="Image" src="https://github.com/user-attachments/assets/79beced3-1cc4-460c-a260-425c9125d875" />

The AppImage is not functioning correctly. When attempting to launch the application, a warning message appears, but the UI fails to render.

Operating System: Manjaro Linux
KDE Plasma Version: 6.5.6
KDE Frameworks Version: 6.24.0
Qt Version: 6.10.2
Kernel Version: 6.12.77-1-MANJARO (64-bit)
Graphics Platform: Wayland

**Comment by pailoro** [comment]
When I take a screenshot or record my screen, I can see the Pluely, so I think the browser will do the same. So, the invisibility  is not working on Ubuntu
