### ISSUE TITLE
Screenshot shortcut key not working on Windows

### ISSUE THREAD

**Issue by shonilchi** [iamsrikanthnani/pluely#54]
### Platform

Windows

### Pluely Version

0.1.3

### Description

whenever I press Ctrl+shift+S to take a screenshot for this app, nothing happens.. what would be the issue here?

**Comment by LuciAkirami** [comment]
Hi @shonilchi , can you provide any recording for the same? I have just installed pluely v0.1.3 on windows 10 and tried the shortcut for screenshot and it works as expected

**Comment by iamsrikanthnani** [comment]
@shonilchi Can you give us more information on when it is not working? Or maybe your PC has already registered those shortcuts with other apps.

**Comment by iamsrikanthnani** [comment]
Hi @shonilchi, this issue might already be fixed in the latest release. Please download the latest version and give it a try.

**Comment by shonilchi** [comment]
Hi, I'm still unable to take a screenshot using the control + shift + s combination in the new 0.1.4 build.  Do I need to have the windows of this Pluely running when I take this screenshot?  and also, is there a way to edit this key combination to something that I want?

**Comment by LuciAkirami** [comment]
That is super weird. I tried both in Windows 10 and Windows 11 and I'm able to take screenshots using the shortcut
